### ISSUE TITLE
Common interface specification

### ISSUE THREAD

**Issue by kdheepak** [NREL/OpenDSSDirect.jl#19]
Hi @tshort,

Would you be interested in having a common `interface` specification between `OpenDSSDirect.jl` 
and `OpenDSSDirect.py`? My understanding is that you are using meta data for each function (in the xlsx file?) to create functions for the user interface. I'm doing something similar, using a [`interface.json`](https://github.com/NREL/OpenDSSDirect.py/blob/master/opendssdirect/_lib/interface.json). It'll be great to combine these, or create a new file that both of us can use, since then any updates to OpenDSS can be implemented in the `interface` specification and then both packages can benefit from this change with little source code updates. Ideally, the `interface` specification would be generated from the OpenDSS DirectDLL interface source code itself.

Thoughts? This is probably not immediately necessary, but will be a great to have in the long run.

**Comment by tshort** [comment]
Yes. I'm interested. I don't actually use the xlsx file. I just used that to create an initial cut at it. JSON's not the easiest format to edit/read (by humans).

**Comment by tshort** [comment]
[TOML](https://github.com/toml-lang/toml) is a decent format. Here's what the start might look like:

```toml

[Basic]

[Basic.NumCircuits]
library = "DSSI"
id = 0
args = 0
doc = "Number of Circuits currently defined"	

[Basic.ClearAll]
library = "DSSI"
id = 1
args = 0
doc = "Clears all circuit definitions"
```

The tough part for julia is that I attach transforms to some of the results. This is nicer in that it transformers results to boolean or complex as needed. I guess those could be Julia-specific fields, but it seems kludgey. 

Also, a question: how much do your names differ from mine?

**Comment by kdheepak** [comment]
I agree that JSON is not the human readable, but programmatically it serves the purpose. This interface.json will primarily be read by the different languages (Julia/Python/others). I have a small preference for JSON since Python has a JSON parser built into the standard library and I would not have to introduce another dependency. But having said that, TOML also looks good and it would be FAR easier editing TOML files as updates later, and hence I'm not be opposed to going that direction. 

If we add a return type field, for e.g. Complex, Float, Str, Array{Complex} etc, to the above we can perform transformations based on the value of that field in both Julia and Python.

The names in OpenDSSDirect.py are identical to the names of the functions in OpenDSSDirect.jl.

**Comment by tshort** [comment]
For me, JSON and TOML both add a dependency. I haven't used either one for programming, so it's hard to say how well either will work for me.

A hesitation I have is that it's a fair bit of work for not much obvious gain. It'd certainly help someone who's trying to port to language X, but we've both got ours done--and hopefully--the interface won't change much. The main benefit is probably tracking down niggling bugs and inconsistencies. I don't know if it's worth it for that. 

I tried plugging your JSON file into an online TOML converter and got an error message something to the effect that "something went horribly wrong" :).

**Comment by kdheepak** [comment]
Haha oh no. I understand your hesitation, it would be a significant rewrite of some core functions on my end as well. I'd still like to do it though, since it would ensure that every time you fix something, I will be able to easily make the same change. 

I've attached a interface.yml [here](https://gist.github.com/kdheepak/f5bf9fe407d0ad6e30f66a319611d80f#file-interface-yml) that I converted from the JSON file. Is YAML something you'd consider? It seems to support more features, has been in use for longer and I would say is also as human readable as TOML.

**Comment by kdheepak** [comment]
Perhaps if I can sharpen my Julia skills ( or use this as an excuse to ), I can submit a PR with these changes based on a YAML / TOML specification for the interface.

**Comment by kdheepak** [comment]
And, with regards to other languages, I've already been asked about implementing a MATLAB interface of the same kind, and I know that at least one colleague is interested in a Node (javascript) implementation. This will definitely be more valuable if those potential packages were also going to use the common specification, so it may be that there is more value in doing this.

**Comment by tshort** [comment]
I prefer TOML for this, but YAML is probably fine as long as the structure of the file is fairly plain. For Julia, I trust the TOML support more than YAML because it's a simpler format.

Interesting news on the MATLAB and JavaScript interest.

**Comment by tshort** [comment]
I emailed back and forth with Davis some today on this topic. He says that the direct-DLL API for OpenDSS will be changing some as features are added with new parallel support. He also mentioned a worry of keeping things consistent. Both of those points support your plan for a common API.

Your offer to submit a PR is best from my point of view 😃. That would be a big help. Before coding, maybe we could take a first cut at deciding the file type and file format. My file-type preferences are in order: TOML, YAML, and lastly JSON.

**Comment by kdheepak** [comment]
Great! Okay, I'll experiment with both YAML and TOML and post here again before I finalize. I agree that JSON is not ideal and that it is on the bottom of my list as well.

**Comment by kdheepak** [comment]
I'm planning to make the specification as a [C header file](https://github.com/kdheepak/OpenDSSDirect.h). Do you see any obvious shortcomings with going down this path?

**Comment by tshort** [comment]
No...

**Comment by kdheepak** [comment]
So in Python there's a [cffi](https://cffi.readthedocs.io/en/latest/overview.html) which I believe allows me to parse a input C header file which then generates the calls automatically. Is there something similar in Julia? 

In any case, I think I'll have all the information in the repo linked above to close this issue. I'll generate the C header file for use in cffi, but also put all the information necessary to generate the C header file in a TOML file.

**Comment by tshort** [comment]
The package [Clang.jl](https://github.com/ihnorton/Clang.jl) can be used to generate Julia interface code from a C header file. I used it a while ago.

**Comment by tshort** [comment]
In that repo you've started, you'll probably need to remove duplicates that are in that `opendssdirect.pas` file.

**Comment by kdheepak** [comment]
Okay great! Then the C header file seems like a good way to go. I'll continue working on it. I'll post here when I make enough progress for you to take a look at.

**Comment by kdheepak** [comment]
The initial version of the file is [here](https://github.com/kdheepak/OpenDSSDirect.schema/blob/master/opendssdirect.h]. I've kept the same names of the types from the OpenDSS source code, made all the arguments lower case and left the function names as is. Next, I'll add the `typedef` for the different types and get this to work in Python using cffi. Once I have the Python versions of these functions, I'll work on the TOML file that describes the interfaces to the functions in the header.

**Comment by kdheepak** [comment]
@tshort I have a TOML + JSON + C header file for OpenDSSDirect. Would you be able to review the [JSON](https://github.com/kdheepak/OpenDSSDirect.schema/blob/master/opendssdirect.json) and [TOML](https://github.com/kdheepak/OpenDSSDirect.schema/blob/master/opendssdirect.toml) files for schema suggestions? The JSON and TOML files are generated from the same Python dictionary. The Python dictionary is generated from OpenDSS source code (using very naive parsing). 

In the JSON file, the first level dictionary is the exported OpenDSS function (see [example](https://github.com/kdheepak/OpenDSSDirect.schema/blob/master/opendssdirect.json#L2-L36) below)

```
     {
        "name":"ActiveClassI",
        "output":{
            "type":"longint"
        },
        "input":[
            {
                "name":"mode",
                "type":"longint"
            },
            {
                "name":"arg",
                "type":"longint"
            }
        ],
        "exported":true,
        "functions":[
            {
                "name":"ActiveClass.First",
                "mode":0
            },
            {
                "name":"ActiveClass.Next",
                "mode":1
            },
            {
                "name":"ActiveClass.NumElements",
                "mode":2
            },
            {
                "name":"ActiveClass.Count",
                "mode":3
            }
        ]
    },
```

This has the fields `name`, `input`, `output`, `exported` and `functions`. `ActiveClassI` is the function that is exported in the library. The `functions` contains the names of the different function to be generated under a "namespace" (e.g. `ActiveClass` is the namespace, and `First`, `Next`, `NumElements`, and `Count` are the functions), along with the value for the argument specified in the `input` field. I haven't finished filling in the full TOML and JSON file yet. I think this is as much as I can do in a naive automated manner. I thought I'd check with you to see if there's anything additional we should add to this.

**Comment by kdheepak** [comment]
I also might change

```
            {
                "name":"ActiveClass.First",
                "mode":0
            },
```

to 

```
            {
                "name":"ActiveClass.First",
                "args": {
                                "name": "mode",
                                "value": 0
                              }
            },
```

**Comment by tshort** [comment]
I'm on vacation and answering on my tablet, so I can't do much in detail. I don't understand the purpose of the two different spec files. Overall, I'm still skeptical that having these huge spec files is an advantage. The toml file is not very readable with all the `module` headings. It'd be better like the example I gave earlier in the thread.

**Comment by kdheepak** [comment]
Thanks for replying when on vacation! Feel free to ignore these messages till you are back at work, there's no rush. 

I think the main value for me is that there's a significant amount of boilerplate required to write these functions in Python, and potentially very similar boilerplate will be required in MATLAB / Java (when someone gets around to it). This could reduce that. Because of the availability of macros in Julia, one may not need the detail in these files.

That said, I'll redo the TOML file based on the example above. I do think only one specification file will be necessary. If I parse the following TOML in Python:

```toml
name = "ActiveClass.First"

[args]
name = "mode"
value = 0
```

Then I can do something like the following:

```python
d = toml.loads(string)
d["name"] # ActiveClass.First
```

However, if I did this in TOML:

```toml
["ActiveClass.First"]
mode = 0
```

Then the key for the dictionary is unknown. I have the loop through the keys to figure out what the keys and their corresponding values are. 

```
d = toml.loads(string)
d["ActiveClass.First"] # {"mode": "0"}
```

As a general practice, I avoid having keys in JSON/TOML be unknown values. It does decrease readability significantly, but makes consuming the data much nicer. 

I'll think about this more. I'll definitely need a schema for OpenDSSDirect.py, and it would be great if this package also used the same, but it's not absolutely necessary. Once I get OpenDSSDirect.py working with the new schema I'll look into making a PR for this, and we can continue the discussion at that point.

**Comment by kdheepak** [comment]
Hi @tshort, as you may have been aware, OpenDSSDirect.py underwent a major rewrite thanks to @PMeira, which cleaned up a lot of the issues in OpenDSSDirect.py. So this particular issue is probably not required anymore. I did want to ask if you were interested in using the [`https://github.com/PMeira/dss_capi`](https://github.com/PMeira/dss_capi) interface in this Julia package, since that has fixed some issues in / made it easier to interface with OpenDSS. Additionally, @PMeira is building the shared library using a common code base on Windows, Mac and Linux using FPC on all platforms. This will ensure that all the versions across Windows, Mac and Linux generate the exact same result for a given version of the package. Currently because OpenDSSDirect.py is using dss_capi, any install of the Python package on any operating system will behave identically. It would be ideal if the Julia interface also worked similarly. Thoughts? If you are interested in doing this, I can submit a PR for this over the next week or so.

**Comment by kdheepak** [comment]
This is much overdue, but I've finally rewritten `OpenDSSDirect.jl` to use the new interface in [`dss_capi`](https://github.com/PMeira/dss_capi). This should fix #25 as well.

<img width="875" alt="screen shot 2019-01-29 at 12 30 22 am" src="https://user-images.githubusercontent.com/1813121/51891780-5797af00-235d-11e9-85d7-a0c84c5486cc.png">

There's a few low level functions that I haven't reimplemented yet, but apart from that all the tests pass! Test coverage also has been improved.

**Comment by kdheepak** [comment]
This is a full rewrite, and I've separated out all the functions into separate modules and files, similar to how it is done in [`OpenDSSDirect.py`](https://github.com/NREL/OpenDSSDirect.py)

<img width="1680" alt="screen shot 2019-01-29 at 12 38 03 am" src="https://user-images.githubusercontent.com/1813121/51892138-34b9ca80-235e-11e9-9aa1-2e4fa4fc2b40.png">

The `build.jl` will also download the corresponding libraries and place them in the appropriate location, so the libraries no longer need to be part of the git repo. 

Given the above, we may want to consider starting the history of this repo from scratch.

@tshort thoughts? Do you want me to submit a PR to this repo or maintain this a separate repo?

**Comment by tshort** [comment]
Wow, that's awesome, @kdheepak! All good news. I really like that libraries are no longer in the repo. 

As far as a separate repo, I'm not really sure. We should work to have just one Julia OpenDSS interface, but we need to figure out where it should sit. The main advantage of staying here is that the Julia package manager can find it. The nice thing about using the NREL site is that it'd sit next to OpenDSSDirect.py.

Given that it's a full rewrite, it makes sense that you have control. So, whether it's here or at the NREL site, you should have complete write access.

Another option is that I transfer this repo to the NREL site. Then you can PR over the top of it. That saves history and issues. And, Julia package manager links still work (they get redirected from here--when a new version is registered, it can use the correct link locations).

Anyway, I'm excited about this. I recently had a request internally to update for Julia v1.0, but I haven't had any time to work on it.

**Comment by kdheepak** [comment]
Thanks for the quick reply! If you want to transfer the repo to the NREL organization that would work great for me. I'd be happy to maintain it and I'll of course add you as a collaborator to the repo with write permissions and state that this was originally your project. Another option is for the NREL organization to fork this repo, but I'm not sure how the Julia package manager links would work in that case.

**Comment by kdheepak** [comment]
This won't be necessary if we transfer, but for the other alternatives, I wonder if changing this [`url`](https://github.com/JuliaLang/METADATA.jl/blob/0f6bdd32b33989689a844586643c0ac932273d3d/OpenDSSDirect/url) is all that is required in order to point the package manager elsewhere. I think at the moment the [Registries](https://github.com/JuliaRegistries/General) are automatically updated based on any changes to the [METADATA.jl](https://github.com/JuliaLang/METADATA.jl/) repo. And the `url` file is the only location where path to the OpenDSSDirect repository is located.

**Comment by tshort** [comment]
I tried to transfer the repo. It failed because I don't have permissions to open a repo at NREL. I thought it would ask you for permission. Did it?

**Comment by kdheepak** [comment]
It may have sent a request to the NREL team that runs the Github organization. I'll get to work in about an hour, I can check in with them and get back to you.
