### ISSUE TITLE
Segmentation fault in getYsparse() on Mac

### ISSUE THREAD

**Issue by kdheepak** [NREL/OpenDSSDirect.jl#25]
Hi @tshort,

Do you happen to know why there is a segfault when calling `getYsparse` on a Mac? [This line](https://github.com/tshort/OpenDSSDirect.jl/blob/cffd7d4b0baee7aec872ed18fcc214bd1351b624/examples/low-level-solver.jl#L143) results in this function never being called in the examples and hence the tests all pass. When I try calling this function it segfaults, the stack trace is below.

```bash
julia> Y = DSSCore.getYsparse()

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
_ZN9KLUSystem12FactorSystemEv at ~/.julia/v0.6/OpenDSSDirect/deps/apple/libklusolve.dylib (unknown line)
FactorSparseMatrix at ~/.julia/v0.6/OpenDSSDirect/deps/apple/libklusolve.dylib (unknown line)
Allocations: 3872081 (Pool: 3870540; Big: 1541); GC: 6
[1]    90509 segmentation fault  julia
```

The segfault happens when `InitAndGetYParams` is called. I get the same segfault in Python.

**Comment by tshort** [comment]
I don't know. I had the same issue on travis, so I added that opt-out. It may be a library problem with the mac dylib. I don't have a mac, so I can't debug more.
